---
- hosts: HAProxy

  vars:
    mysql_1: 10.128.15.203 
    mysql_2: 10.168.0.17
    mysql_3: 10.150.0.10

  tasks:
    - name: CentOS | Update
      become: true
      yum: name=* state=latest
      when: ansible_os_family == "RedHat"

    - name: HAProxy | Install server
      become: true
      yum:
        state: latest
        name: haproxy

    - name: HAProxy | Copy config file
      become: true
      template:
        src: templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg

    - name: HAProxy | Start
      become: true
      service:
        name: haproxy
        state: started
        enabled: yes

    - name: SELinux | Allow connection
      become: true
      command: "setsebool -P haproxy_connect_any=1"
    
    - name: HAProxy | Restart
      become: true
      service:
        name: haproxy
        state: restarted
