---
- hosts: MariaDB

  vars:
    mariadb_new_username: haproxy_root
    mariadb_new_password: password

  tasks:
    - name: CentOS | Update
      become: true
      yum: name=* state=latest
      when: ansible_os_family == "RedHat"

    - name: MariaDB | Copy repo template
      become: true
      template:
        src: templates/mariadb.repo.j2
        dest: /etc/yum.repos.d/mariadb.repo

    - name: MariaDB | Install server
      become: true
      yum:
        state: latest
        name: MariaDB-server

    - name: MariaDB | Install client
      become: true
      yum:
        state: latest
        name: MariaDB-client
        
    - name: MariaDB | Install MariaDB-Python
      become: true
      yum:
        state: latest
        name: MySQL-python

    - name: Selinux | permissive
      become: true
      selinux:
        state: permissive
        policy: targeted

    - name: MariaDB | Start
      become: true
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Firewall | Open port 4567
      become: true
      firewalld:
        port: 4567/tcp
        permanent: true
        state: enabled

    - name: Firewall | Open port 3306
      become: true
      firewalld:
        port: 3306/tcp
        permanent: true
        state: enabled

    - name: Firewall | Open port 873
      become: true
      firewalld:
        port: 873/tcp
        permanent: true
        state: enabled

    - name: Firewall | Open port 4444
      become: true
      firewalld:
        port: 4444/tcp
        permanent: true
        state: enabled


    - name: Firewall | Open port 4567
      become: true
      firewalld:
        port: 4567/tcp
        permanent: true
        state: enabled

    - name: Firewall | Open port 4568
      become: true
      firewalld:
        port: 4568/tcp
        permanent: true
        state: enabled

    - name: Firewall | Open port 9200
      become: true
      firewalld:
        port: 9200/tcp
        permanent: true
        state: enabled

    - name: Firewall | Reload
      become: true
      command: "firewall-cmd --reload"


    - name: MariaDB | Create new user
      mysql_user:
        name: "{{ mariadb_new_username }}"
        password: "{{ mariadb_new_password }}"
        host: "{{ item }}"
        state: present
        priv: '*.*:ALL'
        login_user: root
      with_items:
        - '%'
        - localhost
        - 127.0.0.1
        - ::1

    - name: MariaDB | Create lv316oms database
      mysql_db:
        name: lv316oms
        state: present
        login_user: "{{ mariadb_new_username }}"
        login_password: "{{ mariadb_new_password }}"
     

    - name: MariaDB | Stop
      become: true
      service:
        name: mysql
        state: stopped

    - name: MariaDB | Copy SERVER file
      become: true
      template:
        src: templates/server.cnf.j2
        dest: /etc/my.cnf.d/server.cnf

- hosts: MariaDBMain
  tasks:
      
    - name: MariaDB | Start cluster on 1-st node
      become: true
      command: "galera_new_cluster"

- hosts: MariaDB-sec
  tasks:
    - name: MariaDB | Start cluster on secondary nodes
      become: true
      service:
        name: mysql
        state: started
