---
- hosts: NginxLB
  
  vars:
    tomcat_1: 10.128.0.63 
    tomcat_2: 10.142.0.7
    tomcat_3: 10.138.0.2
  
  tasks:
    - name: CentOS | Update
      become: true
      yum: name=* state=latest
      when: ansible_os_family == "RedHat"
      
    - name: Add epel-release repo
      become: true
      yum:
        name: epel-release
        state: present

    - name: Install nginx
      become: true
      yum:
        name: nginx
        state: present

    - name: Insert nginx.conf
      become: true
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf

    - name: Start NGiNX
      become: true
      service:
        daemon_reload: yes
        name: nginx
        state: started
        enabled: yes

    - name: Start and enable firewalld
      become: true
      service:
        name: firewalld
        state: started
        enabled: yes
      when: ansible_service_mgr == "systemd"

    - name: Open NGiNX port on the firewall
      become: true
      firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
        immediate: yes
      when: ansible_service_mgr == "systemd"
      
    - name: SELinux | Allow connection
      become: true
      command: "setsebool -P httpd_can_network_connect 1"