---
- hosts: Tomcat

  vars:
    tomcat_archive_url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.7/bin/apache-tomcat-9.0.7.tar.gz
    tomcat_archive_dest: /tmp/apache-tomcat-9.0.7.tar.gz
  
  tasks:
    - name: CentOS | Update
      become: true
      yum: name=* state=latest
      when: ansible_os_family == "RedHat"

    - name: Install Java 8 CentOS
      become: true
      yum:
        name: java-1.8.0-openjdk
        state: present
        
    - name: Install basic packages
      become: true
      package:
        name: ['vim','wget','unzip','curl','git']
        state: present
        
    - name: Add tomcat group
      become: true
      group:
        name: tomcat

    - name: Add "tomcat" user
      become: true
      user:
        name: tomcat
        group: tomcat
        home: /opt/tomcat
        createhome: no
        system: yes

    - name: Download Tomcat
      become: true
      get_url:
        url: "{{ tomcat_archive_url }}"
        dest: "{{ tomcat_archive_dest }}"

    - name: Create a tomcat directory
      become: true
      file:
        path: /opt/tomcat
        state: directory
        owner: tomcat
        group: tomcat

    - name: Extract tomcat archive
      become: true
      unarchive:
        src: "{{ tomcat_archive_dest }}"
        dest: /opt/tomcat
        owner: tomcat
        group: tomcat
        remote_src: yes
        extra_opts: "--strip-components=1"
        creates: /opt/tomcat/bin

    - name: Copy tomcat service file
      become: true
      template:
        src: templates/tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service
      when: ansible_service_mgr == "systemd"

    - name: Start and enable tomcat
      become: true
      service:
        daemon_reload: yes
        name: tomcat
        state: started
        enabled: yes
      when: ansible_service_mgr == "systemd"

    - name: Start and enable firewalld
      become: true
      service:
        name: firewalld
        state: started
        enabled: yes
      when: ansible_service_mgr == "systemd"

    - name: Open tomcat port on the firewall
      become: true
      firewalld:
        port: 8080/tcp
        permanent: true
        state: enabled
        immediate: yes
      when: ansible_service_mgr == "systemd"
      
    - name: OMS | Mv war file 
      become: true
      copy:
        src: templates/OMS.war
        dest: /opt/tomcat/webapps
    
